// LVGL 8.4 configuration for the Airstream Weather Panel.
//
// Only the settings that differ from LVGL's defaults are listed. Everything
// else falls through to lv_conf_internal.h, which #ifndef-guards every option,
// so this file stays short and reviewable instead of being a 900-line copy of
// the template that hides the four decisions that actually matter.
#pragma once
#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

// ---------------------------------------------------------------------------
// Color
//
// LV_COLOR_16_SWAP is the one setting that will waste an afternoon if you get
// it wrong. The AXS15231B wants RGB565 big-endian on the wire; the ESP32-S3 is
// little-endian and the SPI peripheral transmits in memory order. Setting this
// to 1 makes LVGL store the bytes pre-swapped so the framebuffer can be handed
// to the SPI DMA engine untouched. Set it to 0 and you get a recognisable but
// lurid image - mostly blue and green where red should be.
// ---------------------------------------------------------------------------
#define LV_COLOR_DEPTH   16
#define LV_COLOR_16_SWAP 1

// ---------------------------------------------------------------------------
// Memory
//
// LVGL's own heap stays in internal SRAM, where it is roughly an order of
// magnitude faster than PSRAM for the many small allocations widget trees make.
// The frame buffer is separate, in PSRAM, allocated in main.cpp.
// ---------------------------------------------------------------------------
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE   (64U * 1024U)

// ---------------------------------------------------------------------------
// Timing
// ---------------------------------------------------------------------------
#define LV_DISP_DEF_REFR_PERIOD  33   // ~30fps
#define LV_INDEV_DEF_READ_PERIOD 20   // 50Hz touch sampling

#define LV_TICK_CUSTOM               1
#define LV_TICK_CUSTOM_INCLUDE       "Arduino.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())

// Gesture distance and long-press timing are NOT settable from here: LVGL 8.4
// hardcodes LV_INDEV_DEF_GESTURE_LIMIT and LV_INDEV_DEF_LONG_PRESS_TIME in
// lv_hal_indev.h without an #ifndef guard, so defining them in lv_conf.h only
// produces a redefinition warning per translation unit and changes nothing.
// They are set on the input device driver at runtime instead - see
// init_lvgl_display() in main.cpp.

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------
#define LV_DRAW_COMPLEX          1   // shadows, masks, arcs
#define LV_SHADOW_CACHE_SIZE     0
#define LV_IMG_CACHE_DEF_SIZE    0

// ---------------------------------------------------------------------------
// Fonts
//
// The five Jost* cuts generated by tools/build_fonts.sh replace LVGL's built-in
// Montserrat entirely. See docs/DESIGN_PROMPT.md for why a geometric sans is
// the right voice for an Airstream.
// ---------------------------------------------------------------------------
#define LV_FONT_MONTSERRAT_8  0
#define LV_FONT_MONTSERRAT_10 0
#define LV_FONT_MONTSERRAT_12 0
#define LV_FONT_MONTSERRAT_14 0
#define LV_FONT_MONTSERRAT_16 0
#define LV_FONT_MONTSERRAT_18 0
#define LV_FONT_MONTSERRAT_20 0
#define LV_FONT_MONTSERRAT_22 0
#define LV_FONT_MONTSERRAT_24 0
#define LV_FONT_MONTSERRAT_26 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_30 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_34 0
#define LV_FONT_MONTSERRAT_36 0
#define LV_FONT_MONTSERRAT_38 0
#define LV_FONT_MONTSERRAT_40 0
#define LV_FONT_MONTSERRAT_42 0
#define LV_FONT_MONTSERRAT_44 0
#define LV_FONT_MONTSERRAT_46 0
#define LV_FONT_MONTSERRAT_48 0

#define LV_FONT_CUSTOM_DECLARE  \
    LV_FONT_DECLARE(font_hero)  \
    LV_FONT_DECLARE(font_title) \
    LV_FONT_DECLARE(font_hour_narrow) \
    LV_FONT_DECLARE(icons_md) \
    LV_FONT_DECLARE(font_body)  \
    LV_FONT_DECLARE(font_label) \
    LV_FONT_DECLARE(font_micro) \
    LV_FONT_DECLARE(icons_lg)   \
    LV_FONT_DECLARE(icons_sm)   \
    LV_FONT_DECLARE(icons_ui)   \
    LV_FONT_DECLARE(icons_xs)

#define LV_FONT_DEFAULT &font_body

// ---------------------------------------------------------------------------
// Widgets we do not use. Trimming these keeps the binary and the LVGL heap
// honest; add one back the moment a future screen needs it.
// ---------------------------------------------------------------------------
#define LV_USE_CALENDAR   0
#define LV_USE_KEYBOARD   0
#define LV_USE_TEXTAREA   0
#define LV_USE_SPINBOX    0
#define LV_USE_COLORWHEEL 0
#define LV_USE_IMGBTN     0
#define LV_USE_TABVIEW    0
#define LV_USE_WIN        0
#define LV_USE_SPAN       0
#define LV_USE_MENU       0
#define LV_USE_METER      0

// The setup screen's Wi-Fi join code (design/SPEC.md §7). LVGL's own encoder,
// ~4KB of flash, no external dependency.
#define LV_USE_QRCODE     1

// ---------------------------------------------------------------------------
// Logging - warnings and errors on the serial console, nothing chattier.
// ---------------------------------------------------------------------------
#define LV_USE_LOG   1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1

// Set to 1 while chasing a frame-rate problem; it draws a live FPS/CPU overlay.
#define LV_USE_PERF_MONITOR 0

#endif // LV_CONF_H
